name = "k-pulse"
compatibility_date = "2025-11-28"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "k_pulse"
database_id = "c602a209-4089-471b-a6c9-27141b626078"

[vars]
# è¨­å?ä¸€çµ„ç®¡?†å??°ï??¨æ–¼è®€?–å?è¦†ï?GETï¼‰æ?æ¬?
ADMIN_KEY = "3ZK7U4IwWtYH8OqBzVn1i5lTJeFRNaoC"
